const Author = require('./Author')
const Comment = require('./Comment')
const Post = require('./Post')

const autor1 = new Author('Rick Riordan')
const public= new Post ('ivro: Percy Jackson e os Olimpianos')
const user1 = new Author('Walker')
const commet1= new Comment('ESTOU MUITO ANIMADO!')
const user2= new Author('Leah')
const comment2= new Comment('ESTOU MUITO ENTUSIASMADA!')
console.log(autor1)
console.log(public)
console.log(user1)
console.log(commet1)
console.log(user2)
console.log(comment2)
