const Author = require('./Author')
const Comment = require('./Comment')
const Post = require('./Post')

const user1 = new Author('Tiana')
const publi= new Post ('Olá sou nova aqui :) essa é minha primira rede social! me ajudem ;-;')
const user2 = new Author('Jordana')
const commet1= new Comment('SEJA BEM VINDA!! :)')
const user3= new Author('Mariana')
const comment2= new Comment('Olá Tiana vamos ser amigas! ')
console.log(user1)
console.log(publi)
console.log(user2)
console.log(commet1)
console.log(user3)
console.log(comment2)